export const wordList = [
    { word: "apple", hint: "fruit" },
    { word: "banana", hint: "fruit" },
    { word: "cherry", hint: "fruit" },
    { word: "peach", hint: "fruit" },
    { word: "grape", hint: "fruit" },
    { word: "lemon", hint: "fruit" },
    { word: "mango", hint: "fruit" },
    { word: "orange", hint: "fruit" },
    { word: "papaya", hint: "fruit" },

    { word: "tiger", hint: "animal" },
    { word: "zebra", hint: "animal" },
    { word: "llama", hint: "animal" },
    { word: "whale", hint: "animal" },
    { word: "koala", hint: "animal" },
    { word: "otter", hint: "animal" },
    { word: "horse", hint: "animal" },
    { word: "goose", hint: "animal" },
    { word: "snail", hint: "animal" },
    { word: "lynx", hint: "animal" },

    { word: "planet", hint: "outer space" },
    { word: "comet", hint: "outer space" },
    { word: "meteor", hint: "outer space" },
    { word: "venus", hint: "outer space" },
    { word: "nebula", hint: "outer space" },
    { word: "galaxy", hint: "outer space" },
    { word: "jupiter", hint: "outer space" },
    { word: "saturn", hint: "outer space" },
    { word: "uranus", hint: "outer space" },
    { word: "star", hint: "outer space" },

    { word: "engine", hint: "machines" },
    { word: "robot", hint: "machines" },
    { word: "laptop", hint: "machines" },
    { word: "printer", hint: "machines" },
    { word: "elevator", hint: "machines" },
    { word: "radio", hint: "machines" },
    { word: "fridge", hint: "machines" },

    { word: "blue", hint: "colors" },
    { word: "green", hint: "colors" },
    { word: "yellow", hint: "colors" },
    { word: "violet", hint: "colors" },
    { word: "orange", hint: "colors" },
    { word: "indigo", hint: "colors" },
    { word: "silver", hint: "colors" },
    { word: "golden", hint: "colors" },
    { word: "bronze", hint: "colors" },
    { word: "purple", hint: "colors" },

    { word: "soccer", hint: "sports" },
    { word: "tennis", hint: "sports" },
    { word: "hockey", hint: "sports" },
    { word: "rugby", hint: "sports" },
    { word: "cricket", hint: "sports" },
    { word: "golf", hint: "sports" },
    { word: "boxing", hint: "sports" },
    { word: "racing", hint: "sports" },
    { word: "judo", hint: "sports" },
    { word: "karate", hint: "sports" }
];
